# GBA 6070 - Programming Foundation for Business Analytics
# Dr. Mohammad Salehan
# Assignment 8 - Multidimensioal Arrays
Runt the cell below to set up your notebook. Each cell should start with np.random.seed(0) to make the results consistent for all students.

In [1]:
import numpy as np
np.random.seed(0)

1. Create a 4x4 array that contains numbers 1-16.

In [4]:
np.random.seed(0)
a = np.arange(1, 17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

2. Create 2 random 4x3 arrays and calculate the sum of their crrosponding elements. Use vectorization for sum calculation.

In [5]:
np.random.seed(0)

a1 = np.random.rand(4, 3)

a2 = np.random.rand(4, 3)

np.sum([a1, a2], axis=0)

array([[1.11685807, 1.640786  , 0.67379943],
       [0.63201248, 0.4438732 , 1.47851396],
       [1.21574396, 1.76178515, 1.9422811 ],
       [1.18260008, 1.2532044 , 1.3094241 ]])

3. Create 2 normally distributed (mean=0, std_dev=1) random 10x5 arrays, stack them vertically, then calculate the average of each column. Use vectorization.

In [7]:
np.random.seed(0)

mu = 0

sigma = 1

a1 = np.random.normal(mu, sigma, size = (10, 5))

a2 = np.random.normal(mu, sigma, size = (10, 5))

at = np.vstack((a1, a2))

np.sum(at, axis = 0) / 10

array([-0.4381154 ,  0.49680203,  0.37280637, -0.61665733,  0.78324448])

4. Create a normally distributed (mean=0, std_dev=1) random 10x5 array, then calculate the sum of the values in each row. Use vectorization.

In [8]:
np.random.seed(0)

mu = 0

sigma = 1

a = np.random.normal(mu, sigma, size = (10, 5))

np.sum(a, axis = 1)

array([ 7.25139873,  0.12883298,  2.92489305,  1.0815671 ,  0.49265458,
        1.40634698, -2.68338442,  1.89938993, -2.73371788, -2.74001743])

5. Create a 5x3 array initialized with random integers 1-10, then reshape it to 3x5, and then calculate its sum (single number fo sum). Use vectorization.

In [9]:
np.random.seed(0)

a = np.random.randint(1, 11, size = (5,3))

np.reshape(a, (3, 5))

np.sum(a)

86

6. Create a 5x3 array initialized with random integers 1-10, then multiply each value by 2. Use vectorization.

In [10]:
np.random.seed(0)

a = np.random.randint(1, 11, size = (5,3))

np.multiply(a, 2)

array([[12,  2,  8],
       [ 8, 16, 20],
       [ 8, 12,  6],
       [10, 16, 14],
       [18, 18,  4]])